/*

This file contains the commands that create the tables for the database

*/
drop table users cascade constraints;
drop table coordinates cascade constraints;
drop table media cascade constraints;
drop table property cascade constraints;

create table property (
    prop_id number NOT NULL,
    prop_name varchar2(50) NOT NULL,
    prop_type varchar2(50) DEFAULT 'Feature',
    prop_acre number DEFAULT 0,
    prop_con_type varchar2(50) DEFAULT NULL,
    prop_desc varchar2(3000) DEFAULT NULL,
    prop_date date DEFAULT NULL,
    prop_pub_acc integer DEFAULT 0 check (prop_pub_acc IN (0,1)),
    prop_geo_type varchar2(50) DEFAULT 'Polygon',
    prop_con_status varchar2(50) check (prop_con_status IN ('Complete','inProgress','Tribal', 'Additional_CE')),
    prop_is_owned integer check (prop_is_owned IN (0,1)),
    PRIMARY KEY (prop_id)
);
  
create table coordinates (
    x_coord number,
    y_coord number,
    prop_id number,
    ord_num int,
    PRIMARY KEY (prop_id, x_coord, y_coord, ord_num),
    FOREIGN KEY (prop_id) references property(prop_id)
);

create table media (
    media_id number,
    media_url varchar2(50),
    media_type varchar2(50),
    prop_id number,
    PRIMARY KEY (media_id),
    FOREIGN KEY (prop_id) references property(prop_id)
);

/*
This is in development and is still working 

CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  password_hash VARCHAR2(256) NOT NULL,
  salt VARCHAR2(256),
  created_at DATE DEFAULT SYSDATE,
  updated_at DATE DEFAULT SYSDATE
);
*/



